# Generated by Django 2.0.6 on 2019-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
