# Generated by Django 2.0.6 on 2019-02-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
