# Generated by Django 2.0.6 on 2019-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190218_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_model',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='pwd',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='sex',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='signup_model',
            name='tel',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
