# Generated by Django 2.0.6 on 2019-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190220_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='id',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
