# Generated by Django 2.0.6 on 2019-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190220_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
    ]
